### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl

### ISSUE THREAD

**Issue by shanerobinson** [22mahmoud/elventy-image-example#1]
Excellent walk through but I'm getting the following error output with a fresh install of your repo. 

Thought you would want to know it's not working if people find your Post and try to use your repo. 😊 

_NOTE: I can get the **Eleventy Img** plugin working fine with [demo code from its README](https://github.com/11ty/eleventy-img/), but not yours._

```javascript
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/shanerobinson/Sites/eleventy-image-example/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/shanerobinson/Sites/eleventy-image-example/node_modules/@11ty/eleventy-img/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/shanerobinson/Sites/eleventy-image-example/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/shanerobinson/Sites/eleventy-image-example/node_modules/@11ty/eleventy-img/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rjdusk** [comment]
I too had the above problem and if anyone stumbles upon this post, my workaround was to point to eleventy-img sharp npm package `const sharp = require("@11ty/eleventy-img/node_modules/sharp");` - The problem is further [discussed over here](https://github.com/lovell/sharp/issues/2337). In short it's an eleventy-img problem.
